import { Issue, Project, User, Workspace } from "./types";

export const mockWorkspace: Workspace = {
    id: "ws-1",
    name: "Figmenta",
    slug: "figmenta",
    icon: "🚀",
    created_at: new Date().toISOString(),
};

export const mockUsers: User[] = [
    {
        id: "user-1",
        email: "admin@figmenta.com",
        name: "Admin User",
        avatar_url: null,
        role: "owner",
        created_at: new Date().toISOString(),
    },
    {
        id: "user-2",
        email: "developer@figmenta.com",
        name: "Dev Team",
        avatar_url: null,
        role: "admin",
        created_at: new Date().toISOString(),
    },
    {
        id: "user-3",
        email: "designer@figmenta.com",
        name: "Design Team",
        avatar_url: null,
        role: "member",
        created_at: new Date().toISOString(),
    },
];

export const mockProjects: Project[] = [
    {
        id: "proj-1",
        name: "Linear Clone",
        description: "Building a high-performance Linear.app clone",
        icon: "📋",
        color: "#5E6AD2",
        workspace_id: "ws-1",
        lead_id: "user-1",
        status: "in-progress",
        start_date: "2024-01-01",
        target_date: "2024-03-01",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "proj-2",
        name: "Discord Copilot",
        description: "Admin-controlled Discord bot",
        icon: "🤖",
        color: "#7289DA",
        workspace_id: "ws-1",
        lead_id: "user-2",
        status: "planned",
        start_date: null,
        target_date: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "proj-3",
        name: "AI Content Studio",
        description: "AI-powered content creation for beauty brands",
        icon: "✨",
        color: "#E91E63",
        workspace_id: "ws-1",
        lead_id: "user-3",
        status: "planned",
        start_date: null,
        target_date: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const mockIssues: Issue[] = [
    {
        id: "issue-1",
        identifier: "LIN-1",
        title: "Set up Next.js project with Tailwind and Shadcn",
        description: "Initialize the project with all required dependencies including Tailwind CSS, Shadcn/ui components, and TypeScript configuration.",
        status: "done",
        priority: "high",
        labels: ["frontend", "feature"],
        assignee_id: "user-1",
        project_id: "proj-1",
        workspace_id: "ws-1",
        created_by: "user-1",
        created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 2,
        parent_id: null,
        order: 1,
    },
    {
        id: "issue-2",
        identifier: "LIN-2",
        title: "Implement Kanban board view",
        description: "Create a drag-and-drop Kanban board with columns for each status. Use dnd-kit for smooth drag interactions.",
        status: "in-progress",
        priority: "high",
        labels: ["frontend", "feature"],
        assignee_id: "user-1",
        project_id: "proj-1",
        workspace_id: "ws-1",
        created_by: "user-1",
        created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 5,
        parent_id: null,
        order: 2,
    },
    {
        id: "issue-3",
        identifier: "LIN-3",
        title: "Add AI-powered task suggestions",
        description: "Integrate Gemini AI to provide smart suggestions for task labels, priority, and task breakdown.",
        status: "todo",
        priority: "medium",
        labels: ["feature", "api"],
        assignee_id: "user-2",
        project_id: "proj-1",
        workspace_id: "ws-1",
        created_by: "user-1",
        created_at: new Date(Date.now() - 86400000).toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 3,
        parent_id: null,
        order: 3,
    },
    {
        id: "issue-4",
        identifier: "LIN-4",
        title: "Implement command palette (Cmd+K)",
        description: "Add a global command palette for quick navigation and actions, similar to Linear's implementation.",
        status: "todo",
        priority: "medium",
        labels: ["frontend", "improvement"],
        assignee_id: null,
        project_id: "proj-1",
        workspace_id: "ws-1",
        created_by: "user-1",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 3,
        parent_id: null,
        order: 4,
    },
    {
        id: "issue-5",
        identifier: "LIN-5",
        title: "Add keyboard shortcuts",
        description: "Implement keyboard shortcuts for common actions like creating issues, changing status, etc.",
        status: "backlog",
        priority: "low",
        labels: ["improvement"],
        assignee_id: null,
        project_id: "proj-1",
        workspace_id: "ws-1",
        created_by: "user-1",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 2,
        parent_id: null,
        order: 5,
    },
    {
        id: "issue-6",
        identifier: "LIN-6",
        title: "Fix issue card hover animation",
        description: "The hover animation on issue cards is slightly laggy. Need to optimize.",
        status: "backlog",
        priority: "low",
        labels: ["bug", "frontend"],
        assignee_id: null,
        project_id: "proj-1",
        workspace_id: "ws-1",
        created_by: "user-2",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 1,
        parent_id: null,
        order: 6,
    },
    {
        id: "issue-7",
        identifier: "LIN-7",
        title: "Set up Discord bot framework",
        description: "Initialize Discord.js project with basic command handling.",
        status: "backlog",
        priority: "high",
        labels: ["backend", "feature"],
        assignee_id: "user-2",
        project_id: "proj-2",
        workspace_id: "ws-1",
        created_by: "user-1",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 3,
        parent_id: null,
        order: 7,
    },
    {
        id: "issue-8",
        identifier: "LIN-8",
        title: "Design brand voice configuration UI",
        description: "Create an intuitive interface for configuring brand voice parameters.",
        status: "backlog",
        priority: "medium",
        labels: ["design", "frontend"],
        assignee_id: "user-3",
        project_id: "proj-3",
        workspace_id: "ws-1",
        created_by: "user-1",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        due_date: null,
        estimate: 4,
        parent_id: null,
        order: 8,
    },
];

let issueCounter = 9;

export function generateIssueId(): string {
    return `issue-${issueCounter++}`;
}

export function generateIssueIdentifier(): string {
    return `LIN-${issueCounter}`;
}
